global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using Microsoft.UI.Xaml;
global using Microsoft.UI.Xaml.Controls;
global using Microsoft.UI.Xaml.Media;
global using Microsoft.UI.Xaml.Navigation;
global using RentalPlanning.Business.Models;
global using RentalPlanning.Infrastructure;
global using System.Collections.Immutable;
global using System.Windows.Input;
global using Windows.ApplicationModel;
global using Windows.Networking.Connectivity;
global using Windows.Storage;
global using Windows.Data;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;

global using RentalPlanning.Models;
global using RentalPlanning.Views;
global using RentalPlanning.CustomElements;
global using RentalPlanning.ViewContent;